(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.VehicleRentalLedger=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const statuses=['RENTING','RETURNED_UNSETTLED','SETTLED'];
function day(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error('日期格式不正确');const n=Date.parse(value+'T00:00:00Z');if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==value)throw new Error('日期不存在');return n/86400000}
function cents(value){if(typeof value!=='number'||!Number.isFinite(value)||value<0||value>1e9)throw new Error('金额必须为有效非负数字');return Math.round((value+Number.EPSILON)*100)}
function calculate(r,today){const end=r.returnDate||today,days=Math.max(0,day(end)-day(r.startDate));const systemCents=r.billingMode==='DAILY'?days*cents(r.dailyRate):Math.round(days*cents(r.monthlyRate)/30);const finalCents=r.manualReceivable==null?systemCents:cents(r.manualReceivable);return {days,systemAmount:systemCents/100,receivable:finalCents/100,outstanding:Math.max(0,finalCents-cents(r.receivedAmount))/100}}
function returnReminder(r,today){
 if(r.status!=='RENTING'||r.returnDate!==null||!r.expectedReturnDate)return null;
 const daysLate=day(today)-day(r.expectedReturnDate);
 return daysLate<0?null:{kind:daysLate===0?'TODAY':'OVERDUE',daysLate};
}
function validate(vehicles,rentals){
 if(!Array.isArray(vehicles)||!Array.isArray(rentals))throw new Error('车辆/出租数据格式异常');
 const ids=new Set(),vins=new Set(),rids=new Set(),active=new Set();const id=x=>typeof x==='string'&&/^[A-Za-z0-9._:-]+$/.test(x);
 for(const v of vehicles){if(!v||!id(v.id)||ids.has(v.id)||typeof v.model!=='string'||!v.model.trim()||typeof v.vin!=='string'||! /^[A-HJ-NPR-Z0-9]{17}$/.test(v.vin)||vins.has(v.vin))throw new Error('车辆ID、车型或VIN无效/重复');ids.add(v.id);vins.add(v.vin);for(const k of ['plateNumber','registrationDate','color'])if(typeof v[k]!=='string')throw new Error('车辆字段异常');if(v.registrationDate)day(v.registrationDate)}
 for(const r of rentals){if(!r||!id(r.id)||rids.has(r.id)||!ids.has(r.vehicleId)||typeof r.renterName!=='string'||!r.renterName.trim()||!statuses.includes(r.status)||!['DAILY','MONTHLY'].includes(r.billingMode)||typeof r.note!=='string')throw new Error('出租记录或车辆关联无效');if(r.renterPhone!==undefined&&(typeof r.renterPhone!=='string'||(r.renterPhone!==''&&!/^[+0-9 ()-]{3,40}$/.test(r.renterPhone))))throw new Error('联系电话格式不正确');if(r.renterContact!==undefined&&(typeof r.renterContact!=='string'||r.renterContact.length>200))throw new Error('联系信息最多200字');if(r.renterIdNumber!==undefined&&(typeof r.renterIdNumber!=='string'||(r.renterIdNumber!==''&&!/^(?:[0-9]{15}|[0-9]{17}[0-9X])$/.test(r.renterIdNumber))))throw new Error('身份证号须为15位或18位，末位可为X');if(r.renterIdPhotos!==undefined&&(!Array.isArray(r.renterIdPhotos)||r.renterIdPhotos.length>2||!r.renterIdPhotos.every(photo=>typeof photo==='string'&&photo.length<=280000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(photo))))throw new Error('身份证照片格式异常或超过大小限制');rids.add(r.id);day(r.startDate);if(r.expectedReturnDate!==undefined&&r.expectedReturnDate!==null&&day(r.expectedReturnDate)<day(r.startDate))throw new Error('约定还车日不能早于放车日');if(r.returnDate!==null){if(day(r.returnDate)<day(r.startDate))throw new Error('还车日不能早于放车日')}if((r.status==='RENTING')!==(r.returnDate===null))throw new Error('还车日期与状态不一致');cents(r.dailyRate);cents(r.monthlyRate);cents(r.receivedAmount);if(cents(r.billingMode==='DAILY'?r.dailyRate:r.monthlyRate)<=0)throw new Error('租金必须大于零');if(r.manualReceivable!==null){cents(r.manualReceivable);if(!r.note.trim())throw new Error('人工调整请填写备注说明')}for(const k of ['createdAt','updatedAt'])if(typeof r[k]!=='string'||!Number.isFinite(Date.parse(r[k])))throw new Error('记录时间无效');if(r.status==='RENTING'){if(active.has(r.vehicleId))throw new Error('该车辆已有在租记录');active.add(r.vehicleId)}if(r.status==='SETTLED'&&calculate(r,r.returnDate).outstanding>0)throw new Error('尚有未收金额，不能标记结清')}
 return true;
}
function validatePaymentSettings(value){
 if(value===undefined)return;
 if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!['CCB','WECHAT'].includes(k)))throw new Error('收款渠道设置格式异常');
 for(const rate of Object.values(value))if(rate!==null&&(typeof rate!=='number'||!Number.isFinite(rate)||rate<0||rate>100))throw new Error('默认手续费率须为0至100之间的百分比');
}
function data(value){if(Array.isArray(value))return {plans:value,vehicles:[],rentals:[]};if(!value||!Array.isArray(value.plans))throw new Error('业务数据结构异常');if(value.schemaVersion!==undefined&&value.schemaVersion!==2)throw new Error('不支持的数据版本');if(value.schemaVersion===2&&(!Array.isArray(value.vehicles)||!Array.isArray(value.rentals)))throw new Error('出租数据包字段缺失');const vehicles=value.vehicles??[],rentals=value.rentals??[];validate(vehicles,rentals);validatePaymentSettings(value.paymentSettings);return {plans:value.plans,vehicles,rentals,...(value.paymentSettings===undefined?{}:{paymentSettings:value.paymentSettings})}}
function pack(plans,vehicles=[],rentals=[],paymentSettings){validate(vehicles,rentals);validatePaymentSettings(paymentSettings);return vehicles.length||rentals.length||paymentSettings!==undefined?{schemaVersion:2,plans,vehicles,rentals,...(paymentSettings===undefined?{}:{paymentSettings})}:plans}
return {validatePaymentSettings,day,calculate,returnReminder,validate,data,pack,statuses};
});
